### ISSUE TITLE
GenStage Producer is being called with handle_info/2 :ok 

### ISSUE THREAD

**Issue by rdalin82** [rdalin82/Twitter-Genstage#1]
```
11:30:16.796 [error] Twitter.Producer Twitter.Producer received unexpected message in handle_info/2: :ok
```
The above is being logged every time a consumer ```handle_events``` is called.  Currently using OTP 20, Elixir 1.4 and deps in mix.exs

**Comment by t56k** [comment]
I was getting this in Elixir 1.5 too. Just implement the `handle_info/2` function on your producer like so:

    def handle_info(_msg, state) do
      {:noreply, [], state}
    end

**Comment by rdalin82** [comment]
Seems to work :+1:  cheers :beer:
